[package]
name = "quixutils"
version = "0.5.0"
authors = ["Prasanna Loganathar <pvl@prasannavl.com>"]
edition = "2018"
description = "Common helpers and utils"
homepage = "https://github.com/quixon-labs/quixutils-rs"
repository = "https://github.com/quixon-labs/quixutils-rs"
readme = "README.md"
keywords = [ "bootstrap", "helpers", "utils" ]
categories = [ "rust-patterns" ]
license = "Apache-2.0"

[dependencies]
log = "0.4"
failure = "0.1"
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.3"
chrono = "0.4"
rand = "0.6"
time = "0.1"
hyper = "0.12"
actix = { version = "0.7", optional = true }
actix-web = { version = "0.7", optional = true }
env_logger = "0.6"

[features]

default = []
# If same name as dependencies can be used, change this.
# https://github.com/rust-lang/cargo/issues/4911
actix_utils = ["actix", "actix-web"]
